# Streamlit Secrets Configuration
# DO NOT commit this file to version control - add to .gitignore

[api_keys]
# SERP API Configuration
serper_api_key = "your_serper_api_key_here"

# OpenAI API Configuration  
openai_api_key = "your_openai_api_key_here"

# DataForSEO API Configuration
dataforseo_login = "your_dataforseo_email@domain.com"
dataforseo_password = "your_dataforseo_password"

# SEMrush API Configuration
semrush_api_key = "your_semrush_api_key_here"

[settings]
# DataForSEO Settings
dataforseo_location_code = 2840  # 2840=US, 2826=UK, 2124=CA

# SEMrush Settings  
semrush_database = "us"  # us, uk, ca, au, de, fr, es, it, br, mx

# Application Settings
default_similarity_threshold = 0.3
default_openai_model = "gpt-4o-mini"
default_label_temperature = 0.3
max_concurrent_requests = 5

# Performance Settings
cache_ttl_hours = 1
enable_parallel_processing = true
max_worker_threads = 4

[costs]
# Cost tracking (USD per 1000 keywords)
dataforseo_clickstream_cost = 0.15
dataforseo_google_ads_cost = 0.075
